{{/* # @formatter:off */}}

{{ if .Values.rbac.serviceAccount.create }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-terraform-module-controller.serviceAccountName" . }}
  labels:
    {{- include "k8s-terraform-module-controller.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{ end }}


{{/* # @formatter:on */}}
