# This is a basic workflow to help you get started with Actions

name: TAG

on:
  create:
    tags:
      - '**'  # all tags

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_modules_container:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build images
        shell: bash
        env:
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: .github/scripts/build-containers.sh "${GITHUB_REF/refs\/tags\//}"
